### ISSUE TITLE
bitwork-client listening adress

### ISSUE THREAD

**Issue by MasterTH-PyPy** [indyjo/bitwrk#111]
the bitwork-client is always just listening on 127.0.0.1:8081. Would be great if it would listen at 0.0.0.0:8081 so other workers can access it.

**Comment by indyjo** [comment]
Good idea! I did some of this a while ago. You can now specify the interface to bind to using the `-intiface` argument. You can also specify `blender-slave.py --listen-port 12345 --listen-iface 1.2.3.4`.
