### ISSUE TITLE
Blender: UI sluggishness

### ISSUE THREAD

**Issue by indyjo** [indyjo/bitwrk#143]
Cyclic probing for a bitwrk client caused sluggishness on some computers/network configurations.

**Comment by Atair1** [comment]
Same here. tried the bitwrk for the first time, and it is unfortunately unusable due to blender locking up every second or so..

**Comment by indyjo** [comment]
@Atair1, the quick fix is to change the timeout in line 43 of bitwrkclient.py from 1 to 0.2 or so.
