### ISSUE TITLE
Check for share relative to binary

### ISSUE THREAD

**Issue by ShayBox** [indyjo/bitwrk#163]
The binary checks for ../share but its relative to the current directory of the user running the command when it should be to the binary file, installing the file into /usr/share/bitwrk-client and /usr/share/bitwrk-client, but being in any other folder than /usr/bin or /usr/share will not find the share folder.

**Comment by indyjo** [comment]
Hi @ShayBox, thanks for reporting this! bitwrk-client relies on finding a path to the binary in argument 0, which in some cases doesn't work. This is easy to fix now that there is os.Executable(), but in the meantime you may resort to passing -resourcedir /some/directory/share/bitwrk-client/

Which platform are you running BitWrk on?
