### ISSUE TITLE
Support for Blender 2.80

### ISSUE THREAD

**Issue by indyjo** [indyjo/bitwrk#177]
Blender 2.80 has been released and is going to be the reference platform in the forseeable future.

 - The add-on works under Blender 2.80
 - Any backwards compatibility workarounds have been removed

**Comment by indyjo** [comment]
Information about API changes: https://wiki.blender.org/wiki/Reference/Release_Notes/2.80/Python_API

**Comment by Mobilpadde** [comment]
Any updates on this? Or should I downgrade blender?

**Comment by indyjo** [comment]
Hi @Mobilpadde, we have found @toymak3r who volunteers to tackle this within our [bounty hunt](http://bitwrk.net/bounty). So, yes, Blender 2.8x support is coming :-)
