### ISSUE TITLE
Blender: Classroom scene renders incorrectly

### ISSUE THREAD

**Issue by indyjo** [indyjo/bitwrk#191]
Something obviously goes wrong when rendering Blender's classroom scene on BitWrk. See https://twitter.com/BitWrk/status/1170695700667084807

**Comment by Nargren** [comment]
Looks like the textures from the assets directory of the demo file are not getting loaded properly by blender.

However, if I run this as a local bitwrk render job, the scene renders just fine. Maybe a remote job issue?

**Comment by indyjo** [comment]
Good observation, so it's probably a library resource that hasn't been remapped. The logic is in [blendfile.py](https://github.com/indyjo/bitwrk/blob/master/bitwrk-blender/render_bitwrk/blendfile.py) if you want to dig further into it (which would be absolutely great, but your info was valuable already!).

Basically, on render time, the BitWrk add-on saves a copy of the blend file, invokes Blender which executes that script and saves the .blend file with modified paths before packing everything into a single binary blob for transfer to the worker.
